In [35]:
import models.HBOSagg
from models.HBOSagg import HBOSAgg
import numpy as np

In [36]:
hbosagg = HBOSAgg(instances=2)

In [37]:
hbosagg.fit(X)

In [38]:
hbosagg.results['decision_scores'].shape

(2, 100)

In [39]:
hbosagg.results['decision_scores']

array([[-0.23352003, -0.16369149, -0.12883212,  0.07721204, -1.7376115 ,
        -0.06894109, -0.41886216, -1.6793402 , -0.41886216, -1.1055251 ,
        -0.32827044, -0.7609186 ,  0.22283612, -1.1178741 , -1.0640599 ,
        -1.1055251 ,  0.21837899, -1.9202437 , -1.9202437 ,  0.05825718,
         0.21837899,  0.11207142, -0.0873669 , -0.5918825 , -0.59633964,
        -1.6793402 , -0.8646216 , -1.1223313 , -0.9228929 ,  0.0233978 ,
        -0.46973583, -0.94355077, -0.7609186 , -0.5380683 , -0.23177287,
        -1.2146702 , -0.70264727, -0.37739694, -0.16369149, -0.5918825 ,
        -0.59633964,  0.05380006, -0.06894109, -0.06894109,  0.05825718,
        -0.23622999, -0.42060933, -0.6183005 , -0.70264727, -0.14118114,
        -0.16369149, -0.1797058 , -0.46973583,  0.27665037, -0.5235501 ,
        -1.3049634 , -1.1223313 , -0.9184358 , -1.1563988 , -0.59633964,
        -0.7564615 , -0.01512685, -0.23797716, -1.2335808 , -0.07339822,
        -1.3973023 , -1.0509486 , -0.41886216, -0.0

In [40]:
hbosagg.results['decision_scores'].transpose()

array([[-0.23352003, -0.78413093],
       [-0.16369149, -0.00330884],
       [-0.12883212, -0.15227275],
       [ 0.07721204, -0.25380123],
       [-1.7376115 , -1.9757798 ],
       [-0.06894109, -0.02017158],
       [-0.41886216, -0.1329333 ],
       [-1.6793402 , -1.4778705 ],
       [-0.41886216, -0.1329333 ],
       [-1.1055251 , -1.1448205 ],
       [-0.32827044, -0.92224544],
       [-0.7609186 , -0.7532522 ],
       [ 0.22283612,  0.98885584],
       [-1.1178741 , -0.46999764],
       [-1.0640599 , -1.3927722 ],
       [-1.1055251 , -1.3980916 ],
       [ 0.21837899,  0.33651617],
       [-1.9202437 , -1.6470988 ],
       [-1.9202437 , -1.1416901 ],
       [ 0.05825718,  0.5565339 ],
       [ 0.21837899, -0.30083394],
       [ 0.11207142,  0.7710667 ],
       [-0.0873669 , -0.6861232 ],
       [-0.5918825 , -0.5337428 ],
       [-0.59633964, -1.044385  ],
       [-1.6793402 , -2.014942  ],
       [-0.8646216 ,  0.14889705],
       [-1.1223313 , -1.2673616 ],
       [-0.9228929 ,

In [41]:
hbosagg.results['bins']

array([4, 7])

In [42]:
hbosagg.results['threshold']

array([0.05380006, 0.0869417 ], dtype=float32)

In [43]:
hbosagg.arr_rank

array([56, 84, 80, 83,  0, 86, 69,  5, 70, 20, 41, 34, 99, 33, 13, 11, 93,
        2,  6, 94, 87, 96, 62, 50, 30,  1, 64, 15, 31, 92, 36, 28, 29, 43,
       74,  8, 23, 32, 81, 49, 52, 90, 82, 79, 95, 85, 67, 35, 45, 68, 57,
       48, 75, 97, 51,  3, 38, 46, 16, 54, 24, 89, 60, 10, 88,  4, 19, 59,
       77, 55, 53, 73, 26, 37, 47, 18, 61, 42, 71, 44, 66, 25, 12, 98, 39,
       63, 17, 65,  7, 58, 40, 14, 76, 21, 22, 72, 91, 27, 78,  9],
      dtype=int64)